### ISSUE TITLE
Implement BLS signature scheme

### ISSUE THREAD

**Issue by nemothenoone** [NilFoundation/crypto3-pubkey#4]
BLS signature scheme implementation is required.

@ilyas675 I would propose to introduce a special branch for this particular task. Something like `3-bls-signature-scheme`.

**Comment by SK0M0R0H** [comment]
Current functionality for aggregatable BLS accordingly to the [specification](https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-04#section-3.3) relies on Knowledge of the Secret Key (or Proof of Possession) or Distinct Messages approaches to defend against [Rogue Public Key Attack](https://medium.com/@coolcottontail/rogue-key-attack-in-bls-signature-and-harmony-security-eac1ea2370ee). 
We cannot control library usage by a third party that could lead to security problems on the user-side. Moreover, some use-cases cannot use both of these methods. 
We can use Boneh-Drijvers-Neven [work](https://crypto.stanford.edu/~dabo/pubs/papers/BLSmultisig.html) on BLS aggregation as an additional (maybe, even default) way to aggregate signatures.

**Comment by ilyas675** [comment]
Complete BLS aggregation functional. TODO:
1) complete public interface for aggregation functions according to the specification
2) implement aggregation functional from Boneh-Drijvers-Neven work
